services:
  app:
    image: 'chatting-backend:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: 'chatting-db:latest'
    build:
      context: ./postgres-db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db/postgres-data:/var/lib/postgresql/data
      - ./postgres-db/ChatWeb.sql:/docker-entrypoint-initdb.d/ChatWeb.sql
    env_file:
      - .env


